
from faker import Factory

fake = Factory.create()

#general urls
registerurl = 'http://www.pragger.com/register'
teamloginurl = 'http://www.pragger.com/login'

#autogeneratedteam
generatedteamname = fake.md5(raw_output=False)
generatedusername = fake.md5(raw_output=False)
generatedemail = fake.email()
defaultpassword = 'pass123'
generatedfirstname = fake.first_name()
generatedlastname = fake.last_name()
generatedteam_subdomain = 'http://' + generatedteamname + '.pragger.com'
generatedteam_dashboard_url = generatedteam_subdomain  + '/dashboard'

#fixed team url
teamname = 'qateam4'
teamsubdomain = 'http://' + teamname + '.pragger.com'
teamdashboardurl = teamsubdomain + '/dashboard'
employeeadminurl = teamsubdomain + '/dashboard/admin_employees'


DICT__teamleaduser = {
 'usernamea': 'teamlead',
 'password' : 'pass123'
}

LIST__employeelist = []

add_x_number_of_employees = 20

for x in range(1, add_x_number_of_employees):

   employeecode=fake.md5(raw_output=False)
   employeeusername=fake.first_name()
   empoloyeeemail=fake.email()
   employeepassword='pass123'
   employeefirstname=fake.first_name()
   employeelastname=fake.last_name()
   LIST__employeelist.append(employeecode+','+ employeeusername +','+empoloyeeemail+ ','+ employeepassword + ',' + employeefirstname + ',' + employeelastname)
			 
			 
			
			
